import type { Rule } from '@react-a11y/core';
import {
  imgAlt,
  anchorHasContent,
  buttonHasName,
  headingHasContent,
  iframeHasTitle,
  htmlHasLang,
  labelInName,
  mediaHasCaptions,
  mediaNoAutoplay,
} from './rules/names.js';
import {
  ariaAttrsValid,
  ariaAttrValueValid,
  roleValid,
  ariaRequiredAttrs,
  ariaHiddenFocusable,
  noRedundantRoles,
  scopeOnTh,
} from './rules/aria.js';
import {
  noStaticElementInteractions,
  mouseEventsHaveKeyEvents,
  noPositiveTabindex,
  noAutofocus,
  noAccessKey,
  noDistractingElements,
  noOutlineNone,
  pointerCancellation,
} from './rules/interactions.js';
import {
  formControlHasLabel,
  anchorIsValid,
  autocompleteValid,
  inputButtonHasName,
  accessibleAuthentication,
  errorIdentification,
  noAutocompleteOff,
} from './rules/forms.js';
import { colorContrast, targetSize } from './rules/contrast.js';
import {
  langValid,
  metaViewportZoomable,
  noMetaRefresh,
  titleHasContent,
} from './rules/document.js';
import {
  headingOrder,
  listStructure,
  tableHasHeader,
  fieldsetHasLegend,
  ariaRequiredContext,
  meaningfulOrder,
  noDuplicateMain,
} from './rules/structure.js';

export { createLabelForPass } from './project/labels.js';

export {
  imgAlt,
  anchorHasContent,
  buttonHasName,
  headingHasContent,
  iframeHasTitle,
  htmlHasLang,
  mediaHasCaptions,
  mediaNoAutoplay,
  ariaAttrsValid,
  ariaAttrValueValid,
  roleValid,
  ariaRequiredAttrs,
  ariaHiddenFocusable,
  noRedundantRoles,
  scopeOnTh,
  noStaticElementInteractions,
  mouseEventsHaveKeyEvents,
  noPositiveTabindex,
  noAutofocus,
  noAccessKey,
  noDistractingElements,
  noOutlineNone,
  formControlHasLabel,
  anchorIsValid,
  autocompleteValid,
  inputButtonHasName,
  accessibleAuthentication,
  langValid,
  metaViewportZoomable,
  noMetaRefresh,
  titleHasContent,
  headingOrder,
  listStructure,
  tableHasHeader,
  fieldsetHasLegend,
  ariaRequiredContext,
  meaningfulOrder,
  noDuplicateMain,
  labelInName,
  pointerCancellation,
  errorIdentification,
  noAutocompleteOff,
  colorContrast,
  targetSize,
};

/** The recommended web preset: every rule, mapped to WCAG 2.2. */
export const webRules: Rule[] = [
  // names & alternatives
  imgAlt,
  anchorHasContent,
  anchorIsValid,
  buttonHasName,
  headingHasContent,
  iframeHasTitle,
  inputButtonHasName,
  // document
  htmlHasLang,
  langValid,
  titleHasContent,
  metaViewportZoomable,
  noMetaRefresh,
  // media
  mediaHasCaptions,
  mediaNoAutoplay,
  // aria
  ariaAttrsValid,
  ariaAttrValueValid,
  roleValid,
  ariaRequiredAttrs,
  ariaRequiredContext,
  ariaHiddenFocusable,
  noRedundantRoles,
  scopeOnTh,
  // structure
  headingOrder,
  listStructure,
  tableHasHeader,
  fieldsetHasLegend,
  noDuplicateMain,
  // interactions & focus
  noStaticElementInteractions,
  mouseEventsHaveKeyEvents,
  noPositiveTabindex,
  noAutofocus,
  noAccessKey,
  noDistractingElements,
  noOutlineNone,
  // forms
  formControlHasLabel,
  autocompleteValid,
  accessibleAuthentication,
  errorIdentification,
  noAutocompleteOff,
  // pointer, contrast & order
  labelInName,
  pointerCancellation,
  colorContrast,
  targetSize,
  meaningfulOrder,
];
